apiVersion: authorino.3scale.net/v1beta1
kind: AuthConfig
metadata:
  name: authorization
spec:
  hosts:
  - auth.kafka.svc
  identity:
  - name: wristband
    oidc:
      endpoint: https://authorino-authorino-oidc.kafka.svc:8083/kafka/authentication/wristband
  response:
  - name: permissions
    wrapper: envoyDynamicMetadata
    json:
      properties:
      - name: rsname
        valueFrom:
          authJSON: auth.identity.rsname
      - name: scopes
        valueFrom:
          authJSON: auth.identity.scopes
