apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.8.0
    replicas: 1
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: oauth
        validIssuerUri: https://authorino-authorino-oidc.kafka.svc:8083/kafka/authentication/wristband
        jwksEndpointUri: https://authorino-authorino-oidc.kafka.svc:8083/kafka/authentication/wristband/.well-known/openid-connect/certs
        userNameClaim: preferred_username
        tlsTrustedCertificates:
        - secretName: authorino-ca-cert
          certificate: ca.crt
    authorization:
      type: keycloak
      tokenEndpointUri: http://auth.kafka.svc:8000/check
      clientId: kafka
      grantsRefreshPeriodSeconds: 10
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    # logging:
    #   type: inline
    #   loggers:
    #     kafka.root.logger.level: "DEBUG"
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

